### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Fuxxing-Wither** [IntriguingTiles/HLFixes#2]
"could not load hl.fix
Please try again at a later time"
i don't know what's going on ,I can't get into the game anymore

**Comment by IntriguingTiles** [comment]
Do you see `hl.fix` in `steamapps\common\Half-Life`?

**Comment by Fuxxing-Wither** [comment]
I uninstalled and reinstalled all the files, and now it's working fine. 
There is one more problem, I often crash when playing alien mods

**Comment by IntriguingTiles** [comment]
Strange. HLFixes itself shouldn't cause any crashes unless the mod is trying to fix what HLFixes has already fixed. What specific mod are you playing? Are you able to consistently get it to crash?

**Comment by Fuxxing-Wither** [comment]
this mod(https://www.moddb.com/mods/alien-mode) 
I think the cause of the crash should not be HLfixes

**Comment by IntriguingTiles** [comment]
Ah, that's my mod actually. If you can send me the latest `crash_hl.exe_...` from `C:\Program Files (x86)\Steam\dumps`, that would be great. Though do note that crash dumps include your computer name, Windows username, and Steam username.

**Comment by Fuxxing-Wither** [comment]
[win11,Wither,Wither.zip](https://github.com/IntriguingTiles/HLFixes/files/11358691/win11.Wither.Wither.zip)

**Comment by IntriguingTiles** [comment]
Looking at the crash dumps, it doesn't seem like my code is involved. If you can get a crash to consistently occur only in Alien Mode, let me know.
